"""
app/services/eta_service.py

Loads the trained LightGBM model ONCE at startup. Model artifacts expected at:
    app/ml_models/eta_lightgbm.txt
    app/ml_models/categorical_maps.json

CHANGELOG (post-review fixes):
- Categorical encoding is now EXPLICIT. We no longer rely on LightGBM's
  internal pandas_categorical remapping happening correctly at predict time
  (a known source of confusion — see github.com/microsoft/LightGBM/pull/5246).
  Instead we force every categorical column to a pd.Categorical with the
  EXACT category list/order recorded during training, read straight out of
  categorical_maps.json. This removes any dependency on LightGBM-version
  behavior or on pandas' default category ordering matching what training saw.
- model_version is now a hash of the actual loaded model file, not a
  hand-maintained string — so it's impossible for the API to report a stale
  version string after a model swap.
- Added run_self_test(), which performs one real prediction against a known
  category from training and checks the result is a finite, sane number.
  This is what /health now calls, instead of just checking is_loaded.
"""

import hashlib
import json
import logging
from pathlib import Path
from typing import Optional, List

import lightgbm as lgb
import pandas as pd

logger = logging.getLogger("eta_service")

MODEL_DIR = Path(__file__).resolve().parent.parent / "ml_models"
MODEL_PATH = MODEL_DIR / "eta_lightgbm.txt"
CATEGORICAL_MAPS_PATH = MODEL_DIR / "categorical_maps.json"

CATEGORICAL_COLS = ["route_id", "segment_id", "segment_type", "time_of_day_bin"]

FEATURE_ORDER = [
    "route_id",
    "segment_id",
    "segment_type",
    "time_of_day_bin",
    "day_of_week",
    "is_weekend",
    "is_holiday",
    "hour_of_day",
    "distance_km",
    "current_speed",
    "previous_segment_speed",
    "weather_severity",
]

# Sane bounds for a single segment's predicted travel time. Used only by the
# self-test to catch "the model loaded but is producing garbage" — not
# enforced on real user requests, since real segments could legitimately be
# outside this range for an unusual route.
SELF_TEST_MIN_SECONDS = 1.0
SELF_TEST_MAX_SECONDS = 7200.0  # 2 hours — generous upper bound for one segment


class EtaModelNotLoadedError(RuntimeError):
    pass


class EtaModelSelfTestError(RuntimeError):
    pass


class EtaService:
    def __init__(self):
        self._model: Optional[lgb.Booster] = None
        self._categorical_maps: dict = {}
        self._category_lists: dict = {}  # col -> ordered list of category strings
        self._model_version: str = "unloaded"
        self._last_self_test_ok: Optional[bool] = None
        self._last_self_test_detail: str = "not run yet"

    def load(self):
        if not MODEL_PATH.exists():
            raise FileNotFoundError(
                f"Model file not found at {MODEL_PATH}. "
                f"Copy it from ml-engine/model/eta_lightgbm.txt first."
            )
        self._model = lgb.Booster(model_file=str(MODEL_PATH))
        self._model_version = self._hash_model_file()

        if not CATEGORICAL_MAPS_PATH.exists():
            raise FileNotFoundError(
                f"categorical_maps.json not found at {CATEGORICAL_MAPS_PATH}. "
                f"This file is REQUIRED — without it, categorical encoding at "
                f"predict time cannot be guaranteed to match training. "
                f"Copy it from ml-engine/model/categorical_maps.json."
            )
        with open(CATEGORICAL_MAPS_PATH) as f:
            raw_maps = json.load(f)

        # Normalize to {col: [category_0, category_1, ...]} regardless of
        # whether the JSON stored keys as int-like strings ("0","1",...) or
        # as a plain list already. Order matters — it must match the
        # category order pandas used during training.
        for col in CATEGORICAL_COLS:
            if col not in raw_maps:
                raise ValueError(
                    f"categorical_maps.json is missing required column '{col}'. "
                    f"Was it generated by the same training run as the model file?"
                )
            col_map = raw_maps[col]
            if isinstance(col_map, dict):
                ordered = [col_map[k] for k in sorted(col_map.keys(), key=lambda x: int(x))]
            elif isinstance(col_map, list):
                ordered = col_map
            else:
                raise ValueError(f"Unrecognized format for categorical_maps.json['{col}']")
            self._category_lists[col] = ordered
            self._categorical_maps[col] = set(ordered)

        logger.info(
            f"ETA model loaded from {MODEL_PATH} (version={self._model_version}). "
            f"Categorical columns: { {c: len(v) for c, v in self._category_lists.items()} }"
        )

        # Run a real prediction immediately so load() fails loudly if
        # something is wrong, rather than surfacing on the first user request.
        self.run_self_test()

    def _hash_model_file(self) -> str:
        h = hashlib.sha256()
        with open(MODEL_PATH, "rb") as f:
            h.update(f.read())
        return h.hexdigest()[:12]

    @property
    def is_loaded(self) -> bool:
        return self._model is not None

    @property
    def model_version(self) -> str:
        return self._model_version

    def _validate_categoricals(self, row: dict):
        for col in CATEGORICAL_COLS:
            known = self._categorical_maps.get(col)
            if known and row.get(col) not in known:
                logger.warning(
                    f"'{row.get(col)}' was not seen during training for column '{col}'. "
                    f"It will be encoded as a missing category (NaN code) by LightGBM — "
                    f"prediction may be unreliable until the model is retrained on this "
                    f"route/segment."
                )

    def _build_dataframe(self, segment: dict) -> pd.DataFrame:
        row = {col: segment.get(col) for col in FEATURE_ORDER}
        df = pd.DataFrame([row])

        # EXPLICIT categorical encoding — this is the core fix. We force each
        # column to a pd.Categorical using the EXACT category list recorded
        # at training time, not whatever pandas would infer from this single
        # row. A value not seen during training correctly becomes NaN/missing
        # (category code -1) rather than silently colliding with category 0.
        for col in CATEGORICAL_COLS:
            df[col] = pd.Categorical(df[col], categories=self._category_lists[col])

        # EXPLICIT numeric coercion — a JSON `null` for current_speed /
        # previous_segment_speed arrives as Python None, which makes pandas
        # build that single-row column as `object` dtype rather than
        # `float64`. LightGBM's predictor expects numeric arrays and throws
        # on an object-dtype column, even though it natively handles NaN
        # just fine. pd.to_numeric(..., errors="coerce") turns None (and any
        # other non-numeric junk) into a proper NaN, which LightGBM treats
        # as "missing" exactly the way training data with dropped GPS pings
        # does. Caught by test_missing_speed_sensor_data_is_allowed.
        numeric_cols = [c for c in FEATURE_ORDER if c not in CATEGORICAL_COLS]
        for col in numeric_cols:
            df[col] = pd.to_numeric(df[col], errors="coerce")

        return df

    def predict_segment_seconds(self, segment: dict) -> float:
        if not self.is_loaded:
            raise EtaModelNotLoadedError("ETA model has not been loaded yet.")

        self._validate_categoricals(segment)
        df = self._build_dataframe(segment)
        prediction = self._model.predict(df)[0]
        return round(float(prediction), 1)

    def predict_trip_seconds(self, segments: List[dict]) -> List[float]:
        return [self.predict_segment_seconds(seg) for seg in segments]

    def run_self_test(self) -> bool:
        """Runs one real prediction using a known-good category combination
        from training data, and checks the output is a finite, sane number.
        This is what /health calls — a model that loads but predicts garbage
        (e.g. due to a broken categorical mapping) will fail this, not just
        report 'loaded: true' and hide the problem."""
        try:
            sample = {
                "route_id": self._category_lists["route_id"][0],
                "segment_id": self._category_lists["segment_id"][0],
                "segment_type": self._category_lists["segment_type"][0],
                "time_of_day_bin": self._category_lists["time_of_day_bin"][0],
                "day_of_week": 1,
                "is_weekend": 0,
                "is_holiday": 0,
                "hour_of_day": 9.0,
                "distance_km": 1.5,
                "current_speed": 15.0,
                "previous_segment_speed": 15.0,
                "weather_severity": 0,
            }
            df = self._build_dataframe(sample)
            result = float(self._model.predict(df)[0])

            if not (result == result):  # NaN check without importing math/numpy here
                raise EtaModelSelfTestError(f"Self-test prediction was NaN: {result}")
            if not (SELF_TEST_MIN_SECONDS <= result <= SELF_TEST_MAX_SECONDS):
                raise EtaModelSelfTestError(
                    f"Self-test prediction {result}s is outside sane bounds "
                    f"[{SELF_TEST_MIN_SECONDS}, {SELF_TEST_MAX_SECONDS}]"
                )

            self._last_self_test_ok = True
            self._last_self_test_detail = f"OK — sample prediction: {round(result, 1)}s"
            logger.info(f"Self-test passed: {self._last_self_test_detail}")
            return True

        except Exception as e:
            self._last_self_test_ok = False
            self._last_self_test_detail = f"FAILED: {e}"
            logger.error(f"Self-test failed: {e}")
            return False

    @property
    def last_self_test_status(self) -> dict:
        return {"ok": self._last_self_test_ok, "detail": self._last_self_test_detail}


eta_service = EtaService()